# - full_name: evga-geforce-rtx-3060-ti-xc-gaming-dual-fan-8gb-gddr6-pcie-40-graphics-card
#   product_id: '631927'
#   simple_name: EVGA RTX 3060
#   store_id: '045'
# - full_name: asus-geforce-rtx-3060-ti-tuf-gaming-overclocked-triple-fan-8gb-gddr6-pcie-40-graphics-card
#   product_id: '631469'
#   simple_name: ASUS GeForce RTX 3060
#   store_id: '045'
# - full_name: asus-geforce-rtx-3060-ti-ko-overclocked-dual-fan-8gb-gddr6-pcie-40-graphics-card
#   product_id: '631474'
#   simple_name: ASUS GeForce RTX 3060 Ti KO Overclocked Dual-Fan 8GB
#   store_id: '045'
# - full_name: msi-geforce-rtx-3060-ti-ventus-2x-overclocked-dual-fan-8gb-gddr6-pcie-40-graphics-card
#   product_id: '631532'
#   simple_name: MSI GeForce RTX 3060 Ti Ventus 2X Overclocked Dual-Fan 8GB
#   store_id: '045'
# - full_name: msi-geforce-rtx-3060-ti-gaming-x-trio-triple-fan-8gb-gddr6-pcie-40-graphics-card
#   product_id: '631531'
#   simple_name: MSI GeForce RTX 3060 Ti Gaming X Trio Triple-Fan 8GB
#   store_id: '045'
# - full_name: gigabyte-geforce-rtx-3060-ti-gaming-pro-overclocked-triple-fan-8gb-gddr6-pcie-40-graphics-card
#   product_id: '631741'
#   simple_name: Gigabyte GeForce RTX 3060 Ti Gaming Pro Overclocked Triple-Fan 8GB
#   store_id: '045'
# - full_name: asus-geforce-rtx-3060-ti-dual-overclocked-dual-fan-8gb-gddr6-pcie-40-graphics-card
#   product_id: '631473'
#   simple_name: ASUS GeForce RTX 3060 Ti Dual Overclocked Dual-Fan 8GB GDDR6 PCIe 4.0
#     Graphics Card
#   store_id: '045'
# - full_name: zotac-geforce-rtx-3060-ti-twin-edge-dual-fan-8gb-gddr6-pcie-40-graphics-card
#   product_id: '631945'
#   simple_name: Zotac GeForce RTX 3060 Ti Twin Edge Dual-Fan 8GB GDDR6 PCIe 4.0 Graphics
#     Card
#   store_id: '045'
# - full_name: nvidia-geforce-rtx-3060-ti-founders-edition-dual-fan-8gb-gddr6-pcie-40-graphics-card
#   product_id: '631716'
#   simple_name: NVIDIA GeForce RTX 3060 Ti Founders Edition Dual-Fan 8GB GDDR6 PCIe
#     4.0 Graphics Card
#   store_id: '045'
# - full_name: gigabyte-geforce-rtx-3060-ti-aorus-master-overclocked-triple-fan-8gb-gddr6-pcie-40-graphics-card
#   product_id: '631740'
#   simple_name: Gigabyte GeForce RTX 3060 Ti Aorus Master Overclocked Triple-Fan 8GB
#     GDDR6 PCIe 4.0 Graphics Card
#   store_id: '045'
- full_name: intel-core-i7-9700k-coffee-lake-36ghz-eight-core-lga-1151-boxed-processor
  product_id: '512484'
  simple_name: Product Image View 0Product Image View 1Product Image View 2 intel LogoIntel Core i7-9700K Coffee Lake 3.6GHz Eight-Core LGA 1151 Boxed Processor
  store_id: '045'